In [92]:
# Installations
!pip install fastdtw

  Created wheel for fastdtw: filename=fastdtw-0.3.4-py3-none-any.whl size=3582 sha256=f3f7053aa1dac0f261cec6724bb230d304ba6238f0b495b9403ab83c956ed81a
  Stored in directory: c:\users\adith\appdata\local\pip\cache\wheels\1f\a1\63\bfd0fddb5bf0b59f564872e29272cee8a2de0cd745d88fede5
Successfully built fastdtw


In [93]:
import pandas as pd
import numpy as np
import ast
from fastdtw import fastdtw
from scipy.spatial.distance import euclidean


# from dtw import *



upload = pd.read_csv('Upload/output.csv')
your_dance = pd.read_csv('Your_Dance/output.csv')


## DTW (Dynamic Time Warping function)

In [94]:
def dtw(s, t, window):
    n, m = len(s), len(t)
    w = np.max([window, abs(n-m)])
    dtw_matrix = np.zeros((n+1, m+1))
    
    for i in range(n+1):
        for j in range(m+1):
            dtw_matrix[i, j] = np.inf
    dtw_matrix[0, 0] = 0
    
    for i in range(1, n+1):
        for j in range(np.max([1, i-w]), np.min([m, i+w])+1):
            dtw_matrix[i, j] = 0
    
    for i in range(1, n+1):
        for j in range(np.max([1, i-w]), np.min([m, i+w])+1):
            cost = abs(s[i-1] - t[j-1])
            # take last min from a square box
            last_min = np.min([dtw_matrix[i-1, j], dtw_matrix[i, j-1], dtw_matrix[i-1, j-1]])
            dtw_matrix[i, j] = cost + last_min
    return dtw_matrix

In [95]:


for i in range(0, upload.shape[0]):
    upload_dict = ast.literal_eval(upload.loc[i, 'landmarks'])
#     upload_data = list(upload_dict.values())
#     upload_nparray = np.array(upload_data)
    temp_df = pd.DataFrame(upload_dict.values())
    print(temp_df)
    print(type(temp_df.loc[0][0]))





           0         1         2
0   0.463933  0.162825 -0.112891
1   0.433306  0.234393  0.055049
2   0.430371  0.233644 -0.240522
3   0.439240  0.359078  0.096957
4   0.436491  0.364944 -0.279772
5   0.448483  0.454242  0.046953
6   0.458007  0.468356 -0.275689
7   0.444939  0.473838  0.092408
8   0.443489  0.475099 -0.092526
9   0.455229  0.613644  0.191467
10  0.459347  0.633649 -0.006003
11  0.423513  0.735104  0.324593
12  0.435138  0.768409  0.120962
13  0.443964  0.769401  0.304220
14  0.470249  0.796185  0.074084
<class 'numpy.float64'>
           0         1         2
0   0.463350  0.158060 -0.090819
1   0.432626  0.230632  0.085452
2   0.430526  0.227831 -0.238818
3   0.438018  0.354731  0.119374
4   0.436008  0.355653 -0.279681
5   0.449292  0.451801  0.061613
6   0.465299  0.460816 -0.272205
7   0.444888  0.461539  0.097456
8   0.442725  0.462634 -0.097558
9   0.462933  0.603408  0.153955
10  0.452484  0.627966 -0.044147
11  0.423539  0.717539  0.261846
12  0.433385  0.770

14  0.485868  0.774673  0.005403
<class 'numpy.float64'>
           0         1         2
0   0.500758  0.168331 -0.062125
1   0.470590  0.237194  0.103534
2   0.470779  0.236384 -0.207520
3   0.475816  0.343883  0.144964
4   0.460241  0.354834 -0.256724
5   0.500399  0.410878  0.095602
6   0.490403  0.439218 -0.275645
7   0.470624  0.457190  0.094749
8   0.477570  0.457250 -0.094724
9   0.484666  0.602836  0.109372
10  0.525114  0.589712 -0.083989
11  0.462715  0.747659  0.160202
12  0.477750  0.713219 -0.013261
13  0.499276  0.783447  0.127753
14  0.506269  0.775089 -0.003166
<class 'numpy.float64'>
           0         1         2
0   0.500630  0.159306 -0.052623
1   0.473796  0.231593  0.106573
2   0.470438  0.228984 -0.178468
3   0.476166  0.340549  0.146785
4   0.453709  0.341272 -0.233113
5   0.505413  0.396117  0.104001
6   0.479147  0.434491 -0.249963
7   0.470682  0.451596  0.089944
8   0.477258  0.450139 -0.089920
9   0.471178  0.600142  0.090476
10  0.527187  0.580641 -0.07

14  0.586066  0.758641  0.071312
<class 'numpy.float64'>
           0         1         2
0   0.519230  0.191524 -0.074086
1   0.495046  0.258098  0.079099
2   0.493357  0.247907 -0.182768
3   0.491005  0.349326  0.118620
4   0.464037  0.343071 -0.229230
5   0.505648  0.430932  0.075130
6   0.479474  0.446243 -0.239662
7   0.487614  0.476201  0.080081
8   0.499137  0.478025 -0.080115
9   0.460768  0.597337  0.132354
10  0.532027  0.598292 -0.009304
11  0.410774  0.707600  0.196485
12  0.540675  0.744862  0.077627
13  0.420887  0.769319  0.165837
14  0.579226  0.760388  0.041937
<class 'numpy.float64'>
           0         1         2
0   0.519372  0.193693 -0.082404
1   0.495539  0.259791  0.070684
2   0.493312  0.252231 -0.200626
3   0.491089  0.356769  0.111477
4   0.467960  0.354087 -0.246260
5   0.500362  0.442386  0.075007
6   0.481813  0.455982 -0.254295
7   0.490937  0.475737  0.083246
8   0.500750  0.477157 -0.083203
9   0.483012  0.598807  0.153052
10  0.534630  0.600534 -0.01

14  0.480908  0.773763 -0.082862
<class 'numpy.float64'>
           0         1         2
0   0.509265  0.173554 -0.044166
1   0.481590  0.242564  0.099257
2   0.478879  0.231841 -0.192778
3   0.482001  0.355066  0.131291
4   0.484994  0.343308 -0.230446
5   0.484725  0.450274  0.086219
6   0.530308  0.411450 -0.212853
7   0.489380  0.452363  0.080349
8   0.480848  0.452729 -0.080422
9   0.520683  0.576579  0.092671
10  0.458924  0.593104 -0.101341
11  0.524588  0.713347  0.174363
12  0.438388  0.739883 -0.054255
13  0.560608  0.741978  0.123936
14  0.471762  0.777006 -0.132227
<class 'numpy.float64'>
           0         1         2
0   0.506868  0.173968 -0.013942
1   0.477486  0.244268  0.117898
2   0.478734  0.233006 -0.176193
3   0.476294  0.355202  0.139583
4   0.485720  0.340903 -0.214704
5   0.479404  0.448155  0.085637
6   0.532451  0.391305 -0.185973
7   0.486817  0.452468  0.084488
8   0.478415  0.453546 -0.084607
9   0.517630  0.578926  0.096372
10  0.449748  0.593636 -0.08

14  0.384871  0.763085 -0.067463
<class 'numpy.float64'>
           0         1         2
0   0.482424  0.209907 -0.071230
1   0.453785  0.277677  0.083112
2   0.457046  0.268143 -0.215283
3   0.460508  0.383888  0.129702
4   0.464609  0.375746 -0.264753
5   0.481187  0.457675  0.084346
6   0.502374  0.450688 -0.261368
7   0.463777  0.477000  0.095126
8   0.462086  0.478644 -0.095214
9   0.479146  0.604967  0.125097
10  0.478572  0.613702 -0.106091
11  0.467866  0.739068  0.223730
12  0.400153  0.696403 -0.010122
13  0.498644  0.757143  0.189564
14  0.400634  0.765263 -0.043818
<class 'numpy.float64'>
           0         1         2
0   0.482292  0.204689 -0.068038
1   0.453776  0.267588  0.084043
2   0.456484  0.262017 -0.211911
3   0.458160  0.378276  0.127943
4   0.459525  0.374451 -0.255540
5   0.466025  0.458950  0.086931
6   0.486295  0.463783 -0.252593
7   0.461269  0.469100  0.094516
8   0.460847  0.469799 -0.094600
9   0.472565  0.604930  0.117514
10  0.482449  0.608083 -0.09

## Upload file CSV to numpy array

In [96]:
upload_complete = []
for i in range(0, upload.shape[0]):
    upload_dict = ast.literal_eval(upload.loc[i, 'landmarks'])
    upload_data = list(upload_dict.values())
    upload_complete.append(upload_data)
#     upload_nparray = np.array(upload_data)
#     np.concatenate((upload_complete_nparray, upload_nparray))
uc_nparray = np.array(upload_complete)
print(uc_nparray)
    

[[[ 0.46393257  0.16282496 -0.11289138]
  [ 0.43330589  0.23439276  0.05504908]
  [ 0.43037093  0.23364367 -0.24052225]
  ...
  [ 0.43513834  0.76840901  0.12096194]
  [ 0.4439638   0.76940084  0.30422041]
  [ 0.47024915  0.79618549  0.07408445]]

 [[ 0.46335039  0.15806007 -0.09081905]
  [ 0.4326258   0.23063187  0.08545221]
  [ 0.43052638  0.22783096 -0.23881838]
  ...
  [ 0.43338504  0.77087134  0.04998247]
  [ 0.43198368  0.76865995  0.23836857]
  [ 0.46778566  0.79982024 -0.01498591]]

 [[ 0.46298352  0.15155087 -0.07830851]
  [ 0.43221056  0.22780553  0.09966643]
  [ 0.43051943  0.22287574 -0.22602822]
  ...
  [ 0.42762181  0.77111149  0.03146775]
  [ 0.44925529  0.76849979  0.2042788 ]
  [ 0.46216786  0.79929382 -0.04304736]]

 ...

 [[ 0.4887335   0.19662462 -0.10431277]
  [ 0.46674171  0.26828596  0.04712088]
  [ 0.45527047  0.26370028 -0.21620598]
  ...
  [ 0.45731106  0.75747865  0.10270779]
  [ 0.45704901  0.74489015  0.25661883]
  [ 0.4877089   0.77958381  0.05292467]]

 [

## Your Dance file CSV to numpy array

In [97]:
your_dance_complete = []
for i in range(0, your_dance.shape[0]):
    your_dance_dict = ast.literal_eval(your_dance.loc[i, 'landmarks'])
    your_dance_data = list(your_dance_dict.values())
    your_dance_complete.append(your_dance_data)
    
ydc_nparray = np.array(your_dance_complete)
print(ydc_nparray)

[[[ 0.62091869  0.52004719 -1.81752551]
  [ 0.94329089  0.97876573 -0.41932884]
  [ 0.26706082  0.95682549 -0.66524482]
  ...
  [ 0.3304908   3.88038421  0.39710709]
  [ 0.68647563  4.15459919 -0.27998272]
  [ 0.40309733  4.14307356 -0.72567791]]

 [[ 0.619192    0.52678984 -1.70950031]
  [ 0.93925035  0.96567851 -0.40781683]
  [ 0.2862919   0.95901924 -0.63465416]
  ...
  [ 0.41107792  3.88033128  0.05275114]
  [ 0.72377127  4.15599108 -0.37798119]
  [ 0.47080916  4.14282131 -0.95205867]]

 [[ 0.61401868  0.52644318 -1.82273066]
  [ 0.93837202  0.96323878 -0.55327988]
  [ 0.28545302  0.96920621 -0.73330683]
  ...
  [ 0.49616337  3.87984395 -0.29326004]
  [ 0.80818808  4.15993357 -0.75987995]
  [ 0.5547756   4.14281702 -1.26727164]]

 ...

 [[ 0.60250407  0.56693202 -1.77363205]
  [ 0.97071874  0.97440618 -0.46542543]
  [ 0.30568328  0.9848538  -0.44598937]
  ...
  [ 0.46403736  4.19837093  0.59743261]
  [ 0.80234593  4.50117493 -0.50516057]
  [ 0.54651034  4.49595833 -0.51825917]]

 [

In [98]:
yd_length = len(ydc_nparray)
u_length = len(uc_nparray)

In [99]:
ydc_nparray[0][1][1]

0.9787657260894775

In [100]:
# if strikes < length difference
# accuracy = 100 - strikes/abs(yd_length-u_length)
# else
strikes = 0
accuracy
len_diff = abs(yd_length - u_length)

for i in range(0,min(yd_length, u_length)):
    for j in range(0, 15):
        for k in range(0, 3):
            if (round(ydc_nparray[i][j][k],2) != round(uc_nparray[i][j][k],2)):
                strikes += 1


if strikes < len_diff:
    accuracy = round((100 - strikes/len_diff), 2)
print(str(round(accuracy * 100, 2))+"%")

score = accuracy * 1000
print(int(score))
            


43.67%
436


## Converting 3D Numpy Array to 1D

In [108]:
ydc = ydc_nparray.ravel()
uc = uc_nparray.ravel()

In [118]:
distance, path = fastdtw(ydc, uc, dist=euclidean)
print(distance)
print(path)

8316.95082416739
[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (6, 7), (6, 8), (6, 9), (7, 10), (8, 11), (9, 12), (10, 13), (11, 14), (12, 15), (13, 16), (14, 17), (15, 18), (16, 19), (17, 20), (18, 21), (19, 22), (20, 23), (21, 24), (22, 25), (23, 26), (24, 27), (25, 28), (26, 29), (27, 30), (28, 31), (29, 32), (30, 33), (31, 34), (32, 34), (33, 34), (34, 34), (35, 34), (36, 35), (37, 36), (38, 36), (39, 37), (40, 37), (41, 38), (42, 39), (43, 40), (44, 41), (45, 42), (46, 43), (47, 44), (48, 45), (49, 46), (50, 47), (51, 48), (51, 49), (51, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 

In [107]:
ydc_nparray

array([[[ 0.62091869,  0.52004719, -1.81752551],
        [ 0.94329089,  0.97876573, -0.41932884],
        [ 0.26706082,  0.95682549, -0.66524482],
        ...,
        [ 0.3304908 ,  3.88038421,  0.39710709],
        [ 0.68647563,  4.15459919, -0.27998272],
        [ 0.40309733,  4.14307356, -0.72567791]],

       [[ 0.619192  ,  0.52678984, -1.70950031],
        [ 0.93925035,  0.96567851, -0.40781683],
        [ 0.2862919 ,  0.95901924, -0.63465416],
        ...,
        [ 0.41107792,  3.88033128,  0.05275114],
        [ 0.72377127,  4.15599108, -0.37798119],
        [ 0.47080916,  4.14282131, -0.95205867]],

       [[ 0.61401868,  0.52644318, -1.82273066],
        [ 0.93837202,  0.96323878, -0.55327988],
        [ 0.28545302,  0.96920621, -0.73330683],
        ...,
        [ 0.49616337,  3.87984395, -0.29326004],
        [ 0.80818808,  4.15993357, -0.75987995],
        [ 0.5547756 ,  4.14281702, -1.26727164]],

       ...,

       [[ 0.60250407,  0.56693202, -1.77363205],
        [ 0